version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "contactbook"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: unless-stopped

  contactbook-app:
    container_name: contactbook-app
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    # Mount local source code into the container to enable live-reloading.
    # Changes to './src' or 'pom.xml' on the host are reflected instantly.
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml

    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  docker-network:
    driver: bridge