spring:
  application:
    name: contactbook
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:15432/contactbook?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

viacep:
  endpoint: https://viacep.com.br/ws

logging:
  level:
    com.victorxavier.contactbook: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      access: read_only
      show-details: always
    metrics:
      access: read_only

server:
  port: 8080