spring:
  application:
    name: contactbook
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:15432/contactbook?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

viacep:
  endpoint: https://viacep.com.br/ws

logging:
  level:
    com.victorxavier.contactbook: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  swagger-ui:
    path: /contactbook/swagger-ui.html

server:
  port: 8080